name: Release

on:
  push:
    branches:
      - main
    tags:        
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Ruby (from .ruby-version)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        
      - name: Run 🚀
        run: bundle exec rake
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Ruby (from .ruby-version)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Push 🚀
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
  
  docs:
    name: Docs
    runs-on: ubuntu-latest
    needs: [test, publish]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Ruby (from .ruby-version)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec rake rdoc
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: doc
          CLEAN: true
